spring:
  application:
    name: myblog

  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    # gmail host= smtp.gmail.com
    host: ${MAIL_SMTP}
    # gmail port= 587
    port: ${MAIL_PORT}
    # goggle username è la mail senza il dominio '@gmail.com'
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
      #create-drop: crea tabelle all'avvio dell'applicazione e le distrugge quando la stoppo
      #validated: confronta entità del progetto con le tabelle del db: se ci sono anomalie, solleva eccezione
      #none: da usare in ambiente di produzione, non viene riportata alcuna modifica al db
      #update: aggiorna il db con le tabelle/colonne nuove; non elimina colonne che non hanno più corrispondenza con l'entità
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    it.cgmconsulting: info
    org.springframework: info
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8081
  servlet:
    context-path: /api
    #context-path: parte di path che si frappone tra host ed endpoint
    #http://{hostname}:{port}/{context-path}/{uri}
    #http://localhost:8081/api/...
  compression:
    enabled: true
    min-response-size: 2KB